# Test playbook
---
- hosts: all
  become: true
  pre_tasks:
    - name: Set NS fact and prometheus netdata hosts
      set_fact:
        namespace: OPENIO
        prometheus_monitored_hosts: [ 'node1' ]
        prometheus_admin_host: 'node1'
        prometheus_provision_only: true
    - name: Seed directory for NS
      file:
        path: /etc/oio/sds/OPENIO
        state: directory
    - name: Seed inventory on nodes
      copy:
        src: inventory.yml
        dest: /etc/oio/sds/OPENIO/inventory.yml
  roles:
    - role: ansible-role-openio-prometheus
...
